FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o core ./cmd/core

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/core .

EXPOSE 50051 8080
CMD ["./core"]
