FROM node:22-alpine3.19 AS builder

WORKDIR /app
COPY web/package*.json ./
RUN npm install

COPY web/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80

# Configure Nginx for SPA, Proxy & Downloads
RUN echo 'server { \
    listen 80; \
    \
    # 1. Frontend (React) \
    location / { \
    root /usr/share/nginx/html; \
    index index.html index.htm; \
    try_files $uri $uri/ /index.html; \
    } \
    \
    # 2. Backend API Proxy \
    location /api/ { \
    proxy_pass http://sentinel_core:8080/api/; \
    proxy_http_version 1.1; \
    proxy_set_header Upgrade $http_upgrade; \
    proxy_set_header Connection "upgrade"; \
    proxy_set_header Host $host; \
    } \
    \
    # 3. Downloads (Agent Binaryleri) \
    location /downloads/ { \
    root /usr/share/nginx/html; \
    autoindex on; \
    } \
    }' > /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]