// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Type int32

const (
	Command_UNKNOWN         Command_Type = 0
	Command_KILL_PROCESS    Command_Type = 1
	Command_RESTART_AGENT   Command_Type = 2
	Command_LIST_PROCESSES  Command_Type = 3
	Command_SYSTEM_REBOOT   Command_Type = 4
	Command_SYSTEM_SHUTDOWN Command_Type = 5
	Command_SYSTEM_SUSPEND  Command_Type = 10
	Command_FETCH_LOGS      Command_Type = 6
	Command_LIST_CONTAINERS Command_Type = 7
	Command_DOCKER_ACTION   Command_Type = 8
	Command_UPDATE_AGENT    Command_Type = 9
	// --- SERVICE MANAGEMENT ---
	Command_LIST_SERVICES  Command_Type = 11
	Command_SERVICE_ACTION Command_Type = 12
)

// Enum value maps for Command_Type.
var (
	Command_Type_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "KILL_PROCESS",
		2:  "RESTART_AGENT",
		3:  "LIST_PROCESSES",
		4:  "SYSTEM_REBOOT",
		5:  "SYSTEM_SHUTDOWN",
		10: "SYSTEM_SUSPEND",
		6:  "FETCH_LOGS",
		7:  "LIST_CONTAINERS",
		8:  "DOCKER_ACTION",
		9:  "UPDATE_AGENT",
		11: "LIST_SERVICES",
		12: "SERVICE_ACTION",
	}
	Command_Type_value = map[string]int32{
		"UNKNOWN":         0,
		"KILL_PROCESS":    1,
		"RESTART_AGENT":   2,
		"LIST_PROCESSES":  3,
		"SYSTEM_REBOOT":   4,
		"SYSTEM_SHUTDOWN": 5,
		"SYSTEM_SUSPEND":  10,
		"FETCH_LOGS":      6,
		"LIST_CONTAINERS": 7,
		"DOCKER_ACTION":   8,
		"UPDATE_AGENT":    9,
		"LIST_SERVICES":   11,
		"SERVICE_ACTION":  12,
	}
)

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}

func (x Command_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_proto_enumTypes[0].Descriptor()
}

func (Command_Type) Type() protoreflect.EnumType {
	return &file_proto_service_proto_enumTypes[0]
}

func (x Command_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Type.Descriptor instead.
func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3, 0}
}

type Telemetry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Telemetry_Handshake
	//	*Telemetry_Metrics
	//	*Telemetry_Response
	Payload       isTelemetry_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *Telemetry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Telemetry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Telemetry) GetPayload() isTelemetry_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Telemetry) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*Telemetry_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *Telemetry) GetMetrics() *MetricData {
	if x != nil {
		if x, ok := x.Payload.(*Telemetry_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *Telemetry) GetResponse() *CommandResponse {
	if x != nil {
		if x, ok := x.Payload.(*Telemetry_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isTelemetry_Payload interface {
	isTelemetry_Payload()
}

type Telemetry_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,3,opt,name=handshake,proto3,oneof"`
}

type Telemetry_Metrics struct {
	Metrics *MetricData `protobuf:"bytes,4,opt,name=metrics,proto3,oneof"`
}

type Telemetry_Response struct {
	Response *CommandResponse `protobuf:"bytes,5,opt,name=response,proto3,oneof"`
}

func (*Telemetry_Handshake) isTelemetry_Payload() {}

func (*Telemetry_Metrics) isTelemetry_Payload() {}

func (*Telemetry_Response) isTelemetry_Payload() {}

type Handshake struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Os                   string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch                 string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname             string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress            string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress           string                 `protobuf:"bytes,14,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	CpuModel             string                 `protobuf:"bytes,5,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCores             int32                  `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	TotalMemory          uint64                 `protobuf:"varint,7,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	TotalDisk            uint64                 `protobuf:"varint,8,opt,name=total_disk,json=totalDisk,proto3" json:"total_disk,omitempty"`
	KernelVersion        string                 `protobuf:"bytes,9,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	BootTime             uint64                 `protobuf:"varint,10,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	Platform             string                 `protobuf:"bytes,11,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformVersion      string                 `protobuf:"bytes,12,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	VirtualizationSystem string                 `protobuf:"bytes,13,opt,name=virtualization_system,json=virtualizationSystem,proto3" json:"virtualization_system,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Handshake) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Handshake) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Handshake) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Handshake) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Handshake) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *Handshake) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Handshake) GetTotalMemory() uint64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *Handshake) GetTotalDisk() uint64 {
	if x != nil {
		return x.TotalDisk
	}
	return 0
}

func (x *Handshake) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *Handshake) GetBootTime() uint64 {
	if x != nil {
		return x.BootTime
	}
	return 0
}

func (x *Handshake) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Handshake) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *Handshake) GetVirtualizationSystem() string {
	if x != nil {
		return x.VirtualizationSystem
	}
	return ""
}

type MetricData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent      float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RamUsedPercent  float64                `protobuf:"fixed64,2,opt,name=ram_used_percent,json=ramUsedPercent,proto3" json:"ram_used_percent,omitempty"`
	DiskUsedPercent float64                `protobuf:"fixed64,3,opt,name=disk_used_percent,json=diskUsedPercent,proto3" json:"disk_used_percent,omitempty"`
	NetSentKbps     float64                `protobuf:"fixed64,4,opt,name=net_sent_kbps,json=netSentKbps,proto3" json:"net_sent_kbps,omitempty"`
	NetRecvKbps     float64                `protobuf:"fixed64,5,opt,name=net_recv_kbps,json=netRecvKbps,proto3" json:"net_recv_kbps,omitempty"`
	TemperatureC    float64                `protobuf:"fixed64,6,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	NetSent         float64                `protobuf:"fixed64,7,opt,name=net_sent,json=netSent,proto3" json:"net_sent,omitempty"`
	NetRecv         float64                `protobuf:"fixed64,8,opt,name=net_recv,json=netRecv,proto3" json:"net_recv,omitempty"`
	Load_1          float64                `protobuf:"fixed64,9,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5          float64                `protobuf:"fixed64,10,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15         float64                `protobuf:"fixed64,11,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	DiskReadMbps    float64                `protobuf:"fixed64,12,opt,name=disk_read_mbps,json=diskReadMbps,proto3" json:"disk_read_mbps,omitempty"`
	DiskWriteMbps   float64                `protobuf:"fixed64,13,opt,name=disk_write_mbps,json=diskWriteMbps,proto3" json:"disk_write_mbps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricData) Reset() {
	*x = MetricData{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricData) ProtoMessage() {}

func (x *MetricData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricData.ProtoReflect.Descriptor instead.
func (*MetricData) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *MetricData) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *MetricData) GetRamUsedPercent() float64 {
	if x != nil {
		return x.RamUsedPercent
	}
	return 0
}

func (x *MetricData) GetDiskUsedPercent() float64 {
	if x != nil {
		return x.DiskUsedPercent
	}
	return 0
}

func (x *MetricData) GetNetSentKbps() float64 {
	if x != nil {
		return x.NetSentKbps
	}
	return 0
}

func (x *MetricData) GetNetRecvKbps() float64 {
	if x != nil {
		return x.NetRecvKbps
	}
	return 0
}

func (x *MetricData) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *MetricData) GetNetSent() float64 {
	if x != nil {
		return x.NetSent
	}
	return 0
}

func (x *MetricData) GetNetRecv() float64 {
	if x != nil {
		return x.NetRecv
	}
	return 0
}

func (x *MetricData) GetLoad_1() float64 {
	if x != nil {
		return x.Load_1
	}
	return 0
}

func (x *MetricData) GetLoad_5() float64 {
	if x != nil {
		return x.Load_5
	}
	return 0
}

func (x *MetricData) GetLoad_15() float64 {
	if x != nil {
		return x.Load_15
	}
	return 0
}

func (x *MetricData) GetDiskReadMbps() float64 {
	if x != nil {
		return x.DiskReadMbps
	}
	return 0
}

func (x *MetricData) GetDiskWriteMbps() float64 {
	if x != nil {
		return x.DiskWriteMbps
	}
	return 0
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  Command_Type           `protobuf:"varint,2,opt,name=type,proto3,enum=sentinel.Command_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_KillProcess
	//	*Command_ListProcesses
	//	*Command_FetchLogs
	//	*Command_ListContainers
	//	*Command_DockerAction
	//	*Command_ListServices
	//	*Command_ServiceAction
	//	*Command_UpdateAgent
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() Command_Type {
	if x != nil {
		return x.Type
	}
	return Command_UNKNOWN
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetKillProcess() *KillProcessRequest {
	if x != nil {
		if x, ok := x.Payload.(*Command_KillProcess); ok {
			return x.KillProcess
		}
	}
	return nil
}

func (x *Command) GetListProcesses() *ListProcessesRequest {
	if x != nil {
		if x, ok := x.Payload.(*Command_ListProcesses); ok {
			return x.ListProcesses
		}
	}
	return nil
}

func (x *Command) GetFetchLogs() *FetchLogsRequest {
	if x != nil {
		if x, ok := x.Payload.(*Command_FetchLogs); ok {
			return x.FetchLogs
		}
	}
	return nil
}

func (x *Command) GetListContainers() *ListContainersRequest {
	if x != nil {
		if x, ok := x.Payload.(*Command_ListContainers); ok {
			return x.ListContainers
		}
	}
	return nil
}

func (x *Command) GetDockerAction() *DockerActionRequest {
	if x != nil {
		if x, ok := x.Payload.(*Command_DockerAction); ok {
			return x.DockerAction
		}
	}
	return nil
}

func (x *Command) GetListServices() *ListServicesRequest {
	if x != nil {
		if x, ok := x.Payload.(*Command_ListServices); ok {
			return x.ListServices
		}
	}
	return nil
}

func (x *Command) GetServiceAction() *ServiceActionRequest {
	if x != nil {
		if x, ok := x.Payload.(*Command_ServiceAction); ok {
			return x.ServiceAction
		}
	}
	return nil
}

func (x *Command) GetUpdateAgent() *UpdateAgentRequest {
	if x != nil {
		if x, ok := x.Payload.(*Command_UpdateAgent); ok {
			return x.UpdateAgent
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_KillProcess struct {
	KillProcess *KillProcessRequest `protobuf:"bytes,3,opt,name=kill_process,json=killProcess,proto3,oneof"`
}

type Command_ListProcesses struct {
	ListProcesses *ListProcessesRequest `protobuf:"bytes,4,opt,name=list_processes,json=listProcesses,proto3,oneof"`
}

type Command_FetchLogs struct {
	FetchLogs *FetchLogsRequest `protobuf:"bytes,5,opt,name=fetch_logs,json=fetchLogs,proto3,oneof"`
}

type Command_ListContainers struct {
	ListContainers *ListContainersRequest `protobuf:"bytes,6,opt,name=list_containers,json=listContainers,proto3,oneof"`
}

type Command_DockerAction struct {
	DockerAction *DockerActionRequest `protobuf:"bytes,7,opt,name=docker_action,json=dockerAction,proto3,oneof"`
}

type Command_ListServices struct {
	ListServices *ListServicesRequest `protobuf:"bytes,8,opt,name=list_services,json=listServices,proto3,oneof"` // --- NEW ---
}

type Command_ServiceAction struct {
	ServiceAction *ServiceActionRequest `protobuf:"bytes,9,opt,name=service_action,json=serviceAction,proto3,oneof"` // --- NEW ---
}

type Command_UpdateAgent struct {
	UpdateAgent *UpdateAgentRequest `protobuf:"bytes,10,opt,name=update_agent,json=updateAgent,proto3,oneof"` // --- NEW ---
}

func (*Command_KillProcess) isCommand_Payload() {}

func (*Command_ListProcesses) isCommand_Payload() {}

func (*Command_FetchLogs) isCommand_Payload() {}

func (*Command_ListContainers) isCommand_Payload() {}

func (*Command_DockerAction) isCommand_Payload() {}

func (*Command_ListServices) isCommand_Payload() {}

func (*Command_ServiceAction) isCommand_Payload() {}

func (*Command_UpdateAgent) isCommand_Payload() {}

type UpdateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAgentRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type KillProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillProcessRequest) Reset() {
	*x = KillProcessRequest{}
	mi := &file_proto_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillProcessRequest) ProtoMessage() {}

func (x *KillProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillProcessRequest.ProtoReflect.Descriptor instead.
func (*KillProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{5}
}

func (x *KillProcessRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ListProcessesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesRequest) Reset() {
	*x = ListProcessesRequest{}
	mi := &file_proto_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesRequest) ProtoMessage() {}

func (x *ListProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessesRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{6}
}

type FetchLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         int32                  `protobuf:"varint,1,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLogsRequest) Reset() {
	*x = FetchLogsRequest{}
	mi := &file_proto_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLogsRequest) ProtoMessage() {}

func (x *FetchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLogsRequest.ProtoReflect.Descriptor instead.
func (*FetchLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{7}
}

func (x *FetchLogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_proto_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{8}
}

// --- NEW SERVICE MESSAGES ---
type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_proto_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{9}
}

type ServiceActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "start", "stop", "restart", "enable", "disable"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceActionRequest) Reset() {
	*x = ServiceActionRequest{}
	mi := &file_proto_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceActionRequest) ProtoMessage() {}

func (x *ServiceActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceActionRequest.ProtoReflect.Descriptor instead.
func (*ServiceActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceActionRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type DockerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "start", "stop", "restart"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerActionRequest) Reset() {
	*x = DockerActionRequest{}
	mi := &file_proto_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerActionRequest) ProtoMessage() {}

func (x *DockerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerActionRequest.ProtoReflect.Descriptor instead.
func (*DockerActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{11}
}

func (x *DockerActionRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DockerActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CommandResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success   bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message   string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to ResultData:
	//
	//	*CommandResponse_ProcessList
	//	*CommandResponse_LogData
	//	*CommandResponse_ContainerList
	//	*CommandResponse_ServiceList
	ResultData    isCommandResponse_ResultData `protobuf_oneof:"result_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{12}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetResultData() isCommandResponse_ResultData {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *CommandResponse) GetProcessList() *ProcessList {
	if x != nil {
		if x, ok := x.ResultData.(*CommandResponse_ProcessList); ok {
			return x.ProcessList
		}
	}
	return nil
}

func (x *CommandResponse) GetLogData() string {
	if x != nil {
		if x, ok := x.ResultData.(*CommandResponse_LogData); ok {
			return x.LogData
		}
	}
	return ""
}

func (x *CommandResponse) GetContainerList() *ContainerList {
	if x != nil {
		if x, ok := x.ResultData.(*CommandResponse_ContainerList); ok {
			return x.ContainerList
		}
	}
	return nil
}

func (x *CommandResponse) GetServiceList() *ServiceList {
	if x != nil {
		if x, ok := x.ResultData.(*CommandResponse_ServiceList); ok {
			return x.ServiceList
		}
	}
	return nil
}

type isCommandResponse_ResultData interface {
	isCommandResponse_ResultData()
}

type CommandResponse_ProcessList struct {
	ProcessList *ProcessList `protobuf:"bytes,4,opt,name=process_list,json=processList,proto3,oneof"`
}

type CommandResponse_LogData struct {
	LogData string `protobuf:"bytes,5,opt,name=log_data,json=logData,proto3,oneof"`
}

type CommandResponse_ContainerList struct {
	ContainerList *ContainerList `protobuf:"bytes,6,opt,name=container_list,json=containerList,proto3,oneof"`
}

type CommandResponse_ServiceList struct {
	ServiceList *ServiceList `protobuf:"bytes,7,opt,name=service_list,json=serviceList,proto3,oneof"` // --- NEW ---
}

func (*CommandResponse_ProcessList) isCommandResponse_ResultData() {}

func (*CommandResponse_LogData) isCommandResponse_ResultData() {}

func (*CommandResponse_ContainerList) isCommandResponse_ResultData() {}

func (*CommandResponse_ServiceList) isCommandResponse_ResultData() {}

type ProcessList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessList) Reset() {
	*x = ProcessList{}
	mi := &file_proto_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessList) ProtoMessage() {}

func (x *ProcessList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessList.ProtoReflect.Descriptor instead.
func (*ProcessList) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{13}
}

func (x *ProcessList) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type ProcessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

type ContainerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerInfo       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerList) Reset() {
	*x = ContainerList{}
	mi := &file_proto_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerList) ProtoMessage() {}

func (x *ContainerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerList.ProtoReflect.Descriptor instead.
func (*ContainerList) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{15}
}

func (x *ContainerList) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`   // "running", "exited"
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // "Up 2 hours"
	CpuPercent    float64                `protobuf:"fixed64,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsage   uint64                 `protobuf:"varint,7,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // Bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_proto_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{16}
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ContainerInfo) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// --- NEW SERVICE TYPES ---
type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_proto_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceList) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	LoadState     string                 `protobuf:"bytes,3,opt,name=load_state,json=loadState,proto3" json:"load_state,omitempty"`       // "loaded", "not-found"
	ActiveState   string                 `protobuf:"bytes,4,opt,name=active_state,json=activeState,proto3" json:"active_state,omitempty"` // "active", "inactive", "failed"
	SubState      string                 `protobuf:"bytes,5,opt,name=sub_state,json=subState,proto3" json:"sub_state,omitempty"`          // "running", "dead"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{18}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceInfo) GetLoadState() string {
	if x != nil {
		return x.LoadState
	}
	return ""
}

func (x *ServiceInfo) GetActiveState() string {
	if x != nil {
		return x.ActiveState
	}
	return ""
}

func (x *ServiceInfo) GetSubState() string {
	if x != nil {
		return x.SubState
	}
	return ""
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\bsentinel\"\xef\x01\n" +
	"\tTelemetry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x123\n" +
	"\thandshake\x18\x03 \x01(\v2\x13.sentinel.HandshakeH\x00R\thandshake\x120\n" +
	"\ametrics\x18\x04 \x01(\v2\x14.sentinel.MetricDataH\x00R\ametrics\x127\n" +
	"\bresponse\x18\x05 \x01(\v2\x19.sentinel.CommandResponseH\x00R\bresponseB\t\n" +
	"\apayload\"\xc7\x03\n" +
	"\tHandshake\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\x0e \x01(\tR\n" +
	"macAddress\x12\x1b\n" +
	"\tcpu_model\x18\x05 \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\x05R\bcpuCores\x12!\n" +
	"\ftotal_memory\x18\a \x01(\x04R\vtotalMemory\x12\x1d\n" +
	"\n" +
	"total_disk\x18\b \x01(\x04R\ttotalDisk\x12%\n" +
	"\x0ekernel_version\x18\t \x01(\tR\rkernelVersion\x12\x1b\n" +
	"\tboot_time\x18\n" +
	" \x01(\x04R\bbootTime\x12\x1a\n" +
	"\bplatform\x18\v \x01(\tR\bplatform\x12)\n" +
	"\x10platform_version\x18\f \x01(\tR\x0fplatformVersion\x123\n" +
	"\x15virtualization_system\x18\r \x01(\tR\x14virtualizationSystem\"\xbb\x03\n" +
	"\n" +
	"MetricData\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12(\n" +
	"\x10ram_used_percent\x18\x02 \x01(\x01R\x0eramUsedPercent\x12*\n" +
	"\x11disk_used_percent\x18\x03 \x01(\x01R\x0fdiskUsedPercent\x12\"\n" +
	"\rnet_sent_kbps\x18\x04 \x01(\x01R\vnetSentKbps\x12\"\n" +
	"\rnet_recv_kbps\x18\x05 \x01(\x01R\vnetRecvKbps\x12#\n" +
	"\rtemperature_c\x18\x06 \x01(\x01R\ftemperatureC\x12\x19\n" +
	"\bnet_sent\x18\a \x01(\x01R\anetSent\x12\x19\n" +
	"\bnet_recv\x18\b \x01(\x01R\anetRecv\x12\x15\n" +
	"\x06load_1\x18\t \x01(\x01R\x05load1\x12\x15\n" +
	"\x06load_5\x18\n" +
	" \x01(\x01R\x05load5\x12\x17\n" +
	"\aload_15\x18\v \x01(\x01R\x06load15\x12$\n" +
	"\x0edisk_read_mbps\x18\f \x01(\x01R\fdiskReadMbps\x12&\n" +
	"\x0fdisk_write_mbps\x18\r \x01(\x01R\rdiskWriteMbps\"\xf9\x06\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.sentinel.Command.TypeR\x04type\x12A\n" +
	"\fkill_process\x18\x03 \x01(\v2\x1c.sentinel.KillProcessRequestH\x00R\vkillProcess\x12G\n" +
	"\x0elist_processes\x18\x04 \x01(\v2\x1e.sentinel.ListProcessesRequestH\x00R\rlistProcesses\x12;\n" +
	"\n" +
	"fetch_logs\x18\x05 \x01(\v2\x1a.sentinel.FetchLogsRequestH\x00R\tfetchLogs\x12J\n" +
	"\x0flist_containers\x18\x06 \x01(\v2\x1f.sentinel.ListContainersRequestH\x00R\x0elistContainers\x12D\n" +
	"\rdocker_action\x18\a \x01(\v2\x1d.sentinel.DockerActionRequestH\x00R\fdockerAction\x12D\n" +
	"\rlist_services\x18\b \x01(\v2\x1d.sentinel.ListServicesRequestH\x00R\flistServices\x12G\n" +
	"\x0eservice_action\x18\t \x01(\v2\x1e.sentinel.ServiceActionRequestH\x00R\rserviceAction\x12A\n" +
	"\fupdate_agent\x18\n" +
	" \x01(\v2\x1c.sentinel.UpdateAgentRequestH\x00R\vupdateAgent\"\xf9\x01\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fKILL_PROCESS\x10\x01\x12\x11\n" +
	"\rRESTART_AGENT\x10\x02\x12\x12\n" +
	"\x0eLIST_PROCESSES\x10\x03\x12\x11\n" +
	"\rSYSTEM_REBOOT\x10\x04\x12\x13\n" +
	"\x0fSYSTEM_SHUTDOWN\x10\x05\x12\x12\n" +
	"\x0eSYSTEM_SUSPEND\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"FETCH_LOGS\x10\x06\x12\x13\n" +
	"\x0fLIST_CONTAINERS\x10\a\x12\x11\n" +
	"\rDOCKER_ACTION\x10\b\x12\x10\n" +
	"\fUPDATE_AGENT\x10\t\x12\x11\n" +
	"\rLIST_SERVICES\x10\v\x12\x12\n" +
	"\x0eSERVICE_ACTION\x10\fB\t\n" +
	"\apayload\"7\n" +
	"\x12UpdateAgentRequest\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\"&\n" +
	"\x12KillProcessRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"\x16\n" +
	"\x14ListProcessesRequest\"(\n" +
	"\x10FetchLogsRequest\x12\x14\n" +
	"\x05lines\x18\x01 \x01(\x05R\x05lines\"\x17\n" +
	"\x15ListContainersRequest\"\x15\n" +
	"\x13ListServicesRequest\"Q\n" +
	"\x14ServiceActionRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"P\n" +
	"\x13DockerActionRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xca\x02\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12:\n" +
	"\fprocess_list\x18\x04 \x01(\v2\x15.sentinel.ProcessListH\x00R\vprocessList\x12\x1b\n" +
	"\blog_data\x18\x05 \x01(\tH\x00R\alogData\x12@\n" +
	"\x0econtainer_list\x18\x06 \x01(\v2\x17.sentinel.ContainerListH\x00R\rcontainerList\x12:\n" +
	"\fservice_list\x18\a \x01(\v2\x15.sentinel.ServiceListH\x00R\vserviceListB\r\n" +
	"\vresult_data\"B\n" +
	"\vProcessList\x123\n" +
	"\tprocesses\x18\x01 \x03(\v2\x15.sentinel.ProcessInfoR\tprocesses\"{\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\"H\n" +
	"\rContainerList\x127\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x17.sentinel.ContainerInfoR\n" +
	"containers\"\xbb\x01\n" +
	"\rContainerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_usage\x18\a \x01(\x04R\vmemoryUsage\"@\n" +
	"\vServiceList\x121\n" +
	"\bservices\x18\x01 \x03(\v2\x15.sentinel.ServiceInfoR\bservices\"\xa2\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"load_state\x18\x03 \x01(\tR\tloadState\x12!\n" +
	"\factive_state\x18\x04 \x01(\tR\vactiveState\x12\x1b\n" +
	"\tsub_state\x18\x05 \x01(\tR\bsubState2N\n" +
	"\rSystemMonitor\x12=\n" +
	"\x0fStreamTelemetry\x12\x13.sentinel.Telemetry\x1a\x11.sentinel.Command(\x010\x01B$Z\"github.com/gigabyte/sentinel/protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_service_proto_goTypes = []any{
	(Command_Type)(0),             // 0: sentinel.Command.Type
	(*Telemetry)(nil),             // 1: sentinel.Telemetry
	(*Handshake)(nil),             // 2: sentinel.Handshake
	(*MetricData)(nil),            // 3: sentinel.MetricData
	(*Command)(nil),               // 4: sentinel.Command
	(*UpdateAgentRequest)(nil),    // 5: sentinel.UpdateAgentRequest
	(*KillProcessRequest)(nil),    // 6: sentinel.KillProcessRequest
	(*ListProcessesRequest)(nil),  // 7: sentinel.ListProcessesRequest
	(*FetchLogsRequest)(nil),      // 8: sentinel.FetchLogsRequest
	(*ListContainersRequest)(nil), // 9: sentinel.ListContainersRequest
	(*ListServicesRequest)(nil),   // 10: sentinel.ListServicesRequest
	(*ServiceActionRequest)(nil),  // 11: sentinel.ServiceActionRequest
	(*DockerActionRequest)(nil),   // 12: sentinel.DockerActionRequest
	(*CommandResponse)(nil),       // 13: sentinel.CommandResponse
	(*ProcessList)(nil),           // 14: sentinel.ProcessList
	(*ProcessInfo)(nil),           // 15: sentinel.ProcessInfo
	(*ContainerList)(nil),         // 16: sentinel.ContainerList
	(*ContainerInfo)(nil),         // 17: sentinel.ContainerInfo
	(*ServiceList)(nil),           // 18: sentinel.ServiceList
	(*ServiceInfo)(nil),           // 19: sentinel.ServiceInfo
}
var file_proto_service_proto_depIdxs = []int32{
	2,  // 0: sentinel.Telemetry.handshake:type_name -> sentinel.Handshake
	3,  // 1: sentinel.Telemetry.metrics:type_name -> sentinel.MetricData
	13, // 2: sentinel.Telemetry.response:type_name -> sentinel.CommandResponse
	0,  // 3: sentinel.Command.type:type_name -> sentinel.Command.Type
	6,  // 4: sentinel.Command.kill_process:type_name -> sentinel.KillProcessRequest
	7,  // 5: sentinel.Command.list_processes:type_name -> sentinel.ListProcessesRequest
	8,  // 6: sentinel.Command.fetch_logs:type_name -> sentinel.FetchLogsRequest
	9,  // 7: sentinel.Command.list_containers:type_name -> sentinel.ListContainersRequest
	12, // 8: sentinel.Command.docker_action:type_name -> sentinel.DockerActionRequest
	10, // 9: sentinel.Command.list_services:type_name -> sentinel.ListServicesRequest
	11, // 10: sentinel.Command.service_action:type_name -> sentinel.ServiceActionRequest
	5,  // 11: sentinel.Command.update_agent:type_name -> sentinel.UpdateAgentRequest
	14, // 12: sentinel.CommandResponse.process_list:type_name -> sentinel.ProcessList
	16, // 13: sentinel.CommandResponse.container_list:type_name -> sentinel.ContainerList
	18, // 14: sentinel.CommandResponse.service_list:type_name -> sentinel.ServiceList
	15, // 15: sentinel.ProcessList.processes:type_name -> sentinel.ProcessInfo
	17, // 16: sentinel.ContainerList.containers:type_name -> sentinel.ContainerInfo
	19, // 17: sentinel.ServiceList.services:type_name -> sentinel.ServiceInfo
	1,  // 18: sentinel.SystemMonitor.StreamTelemetry:input_type -> sentinel.Telemetry
	4,  // 19: sentinel.SystemMonitor.StreamTelemetry:output_type -> sentinel.Command
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	file_proto_service_proto_msgTypes[0].OneofWrappers = []any{
		(*Telemetry_Handshake)(nil),
		(*Telemetry_Metrics)(nil),
		(*Telemetry_Response)(nil),
	}
	file_proto_service_proto_msgTypes[3].OneofWrappers = []any{
		(*Command_KillProcess)(nil),
		(*Command_ListProcesses)(nil),
		(*Command_FetchLogs)(nil),
		(*Command_ListContainers)(nil),
		(*Command_DockerAction)(nil),
		(*Command_ListServices)(nil),
		(*Command_ServiceAction)(nil),
		(*Command_UpdateAgent)(nil),
	}
	file_proto_service_proto_msgTypes[12].OneofWrappers = []any{
		(*CommandResponse_ProcessList)(nil),
		(*CommandResponse_LogData)(nil),
		(*CommandResponse_ContainerList)(nil),
		(*CommandResponse_ServiceList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		EnumInfos:         file_proto_service_proto_enumTypes,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
