// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemMonitor_StreamTelemetry_FullMethodName = "/sentinel.SystemMonitor/StreamTelemetry"
)

// SystemMonitorClient is the client API for SystemMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemMonitorClient interface {
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Telemetry, Command], error)
}

type systemMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemMonitorClient(cc grpc.ClientConnInterface) SystemMonitorClient {
	return &systemMonitorClient{cc}
}

func (c *systemMonitorClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Telemetry, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemMonitor_ServiceDesc.Streams[0], SystemMonitor_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Telemetry, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamTelemetryClient = grpc.BidiStreamingClient[Telemetry, Command]

// SystemMonitorServer is the server API for SystemMonitor service.
// All implementations must embed UnimplementedSystemMonitorServer
// for forward compatibility.
type SystemMonitorServer interface {
	StreamTelemetry(grpc.BidiStreamingServer[Telemetry, Command]) error
	mustEmbedUnimplementedSystemMonitorServer()
}

// UnimplementedSystemMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemMonitorServer struct{}

func (UnimplementedSystemMonitorServer) StreamTelemetry(grpc.BidiStreamingServer[Telemetry, Command]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedSystemMonitorServer) mustEmbedUnimplementedSystemMonitorServer() {}
func (UnimplementedSystemMonitorServer) testEmbeddedByValue()                       {}

// UnsafeSystemMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemMonitorServer will
// result in compilation errors.
type UnsafeSystemMonitorServer interface {
	mustEmbedUnimplementedSystemMonitorServer()
}

func RegisterSystemMonitorServer(s grpc.ServiceRegistrar, srv SystemMonitorServer) {
	// If the following call panics, it indicates UnimplementedSystemMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemMonitor_ServiceDesc, srv)
}

func _SystemMonitor_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SystemMonitorServer).StreamTelemetry(&grpc.GenericServerStream[Telemetry, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemMonitor_StreamTelemetryServer = grpc.BidiStreamingServer[Telemetry, Command]

// SystemMonitor_ServiceDesc is the grpc.ServiceDesc for SystemMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.SystemMonitor",
	HandlerType: (*SystemMonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _SystemMonitor_StreamTelemetry_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}
